{% set name = "ijava" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JaneliaSciComp/IJava/releases/download/v{{ version }}/IJava-{{ version }}.tar.gz
  sha256: 9e964cc23b5338f17aeedbb6ff2258067d7adcf8e6d8f42fa3c6e3b4ff29bd39

build:
  noarch: generic
  number: 0

requirements:
  build:
    - openjdk <18
    - python
    - unzip  # [not win]
    - jupyter
  host:
    - python
    - jupyter
  run:
    - openjdk
    - jupyter

test:
  imports:
    - jupyter_client

about:
  home: https://github.com/JaneliaSciComp/IJava
  summary: 'A Jupyter kernel for executing Java code.'
  description: |
    A Jupyter kernel for executing Java code. The kernel executes code via the new JShell tool.
    Some of the additional commands should be supported as needed via a syntax similar to the
    ipython magics. This is from a fork by the HHMI Janelia Research Campus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/JaneliaSciComp/IJava
  dev_url: https://github.com/JaneliaSciComp/IJava

extra:
  recipe-maintainers:
    - mkitti
